lucky_numbers= [4, 8, 5, 15, 16, 23, 42]
friends = ["Kevin", "Karen", "Jim", "Jim", "Toby", "Oscar", "Romero"]
# friends.extend(lucky_numbers)
# print(friends)
friends.append("Coder")
print(friends)
friends.insert(1, "kala la la")
print(friends)
friends.remove("kala la la")
print(friends)
friends.pop()
print(friends)
friends.sort()
print(friends)
lucky_numbers.sort()
print(lucky_numbers)
print(friends.index("Oscar"))
print(friends.count("Jim"))
# friends.clear()
# print(friends)
lucky_numbers.reverse()
print(lucky_numbers)
friends2 = friends.copy()
print(friends2)
friends3 = friends.copy()
friends.sort()
friends3.reverse()
print(friends3)