print("Love Letter Mad Lib")
print()
person = input("Enter A Name Of A Person: ")
adjective = input("Enter A Adjective: ")
verb = input("Enter A Verb: ")
body_part = input("Enter A Name of A Body Part: ")
number = input("Enter A Number: ")
noun = input("Enter A Noun: ")
adverb = input("Enter An Adverb: ")
verb_2 = input("Enter Another Verb: ")
plural_Pronoun = input("Enter A Plural Pronoun: ")
your_Name = input("Enter Your Name: ")
print("--------------------------------------------")
print("")
print("Dear " + person + ",")
print("You are extremly " + adjective + " and I " + verb + " you!")
print("I want to kiss your " + body_part + " " + number + " times. You make my " + noun + " burn with desire. ")
print("When I first saw you, I " + adverb + " stared at you and fell in love.")
print("Will you " + verb_2 + " out with me?")
print("Don`t let your parents discourage you, those " + plural_Pronoun + " are just jealous.")
print("Yours forever, " + your_Name )
print("")
print("--------------------------------------------")
